version: '3.7'
services:
  chrome:
    image: seleniarm/standalone-chromium:latest
    container_name: boomkat-scrapper
    hostname: chrome
    ports:
      - 4445:4444

  web:
    build:
      context: .
      dockerfile: Dockerfile.arm
    container_name: boomkat-fastapi
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8001:8000
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
